service: myfreshword
runtime: php55

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/techloft-173609:europe-west1:techloft-db1;dbname=myfreshword
  MYSQL_USER: mac
  MYSQL_PASSWORD: Some1ilove
  MYSQL_DB: myfreshword

beta_settings:
    cloud_sql_instances: "techloft-173609:europe-west1:techloft-db1"

handlers:
- url: /
  script: index.php

- url: /(.+)
  script: index.php

- url: /(.+\.(eot|otf|tt[cf]|woff2?|cur|gif|ico|jpe?g|png|svgz?|webp))
  static_files: \1
  upload: (.+\.(eot|otf|tt[cf]|woff2?|cur|gif|ico|jpe?g|png|svgz?|webp))
  http_headers:
    # Allow cross-origin access to web fonts and images
    # You can also replace "*" with a specific host, e.g. https://example.org
    Access-Control-Allow-Origin: "*"
