service: myfreshword
runtime: php55

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/techloft-173609:europe-west1:techloft-db1;dbname=myfreshword
  MYSQL_USER: mac
  MYSQL_PASSWORD: Some1ilove
  MYSQL_DB: myfreshword

beta_settings:
    cloud_sql_instances: "techloft-173609:europe-west1:techloft-db1"

handlers:
- url: /
  http_headers:
    Access-Control-Allow-Origin: '*'
  script: index.php
- url: /(.+)
  http_headers:
    Access-Control-Allow-Origin: '*'
  script: index.php
