steps:

- id: build
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud source repos clone myfreshword_api --project=techloft-173609
    cd myfreshword_api
    ls -a
    git checkout master
    gcloud app deploy app.yaml
